name: 每日資安快訊

on:
  schedule:
    - cron: '0 23 * * *'  # 每天台灣時間 07:00 執行（UTC 23:00）
  workflow_dispatch:  # 允許手動觸發

permissions:
  contents: write #允許Actions推送內容到倉庫

jobs:
  fetch-and-summarize-news:
    runs-on: ubuntu-latest

    steps:
      - name: 取得 Repository
        uses: actions/checkout@v4

      - name: 設置 Python 環境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安裝 Python 依賴套件
        run: pip install -r requirements.txt

      - name: 抓取資安新聞連結
        run: python scripts/fetch_news_link.py

      - name: 抓取資安新聞(markdown格式)
        run: python scripts/download_articles_markdown.py
      - name: Archive coverage results
        uses: actions/upload-artifact@v4
        with:
          name: data-report
          path: ./
  
